apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-web
  labels:
    app: golang-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-web
  strategy: 
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        app: golang-web
    spec:
      containers:
      - name: golang-web
        image: asia.gcr.io/expanded-dryad-356011/bazel-golang:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: golang-port