apiVersion: v1
kind: Service
metadata:
  labels:
    app: golang-web-svc
  #nnotations:
  # cloud.google.com/load-balancer-type: "Internal"
  name: golang-web-svc
spec:
  ports:
  - name: tcp-golang
    port: 8080
    protocol: TCP
  selector:
    app: golang-web
  type: NodePort